# Data preprocessing for crossfit data
**Steps:**
- Import data
- Drop unwanted columns [ID,Names,team,affiliate]
- deal with Nan values
- feature engineer

In [19]:
# Importing essential libraries for preprocessing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
### Step 1 ###

#importing and defining data
pd.set_option('display.max_columns',None) # So all columns get shown 
df= pd.read_csv('athletes.csv') # Reading data into df
df.head() # Checking first 5 rows of data

,athlete_id,name,region,team,affiliate,gender,age,height,weight,fran,helen,grace,filthy50,fgonebad,run400,run5k,candj,snatch,deadlift,backsq,pullups,eat,train,background,experience,schedule,howlong
0,2554.0,Pj Ablang,South West,Double Edge,Double Edge CrossFit,Male,24.0,70.0,166.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,220.0,NaN,400.0,305.0,NaN,NaN,I workout mostly at a CrossFit Affiliate|I hav...,I played youth or high school level sports|I r...,I began CrossFit with a coach (e.g. at an affi...,I do multiple workouts in a day 2x a week|,4+ years|
1,3517.0,Derek Abdella,NaN,NaN,NaN,Male,42.0,70.0,190.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have a coach who determines my programming|I...,I played youth or high school level sports|,I began CrossFit with a coach (e.g. at an affi...,I do multiple workouts in a day 2x a week|,4+ years|
2,4691.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5164.0,Abo Brandon,Southern California,LAX CrossFit,LAX CrossFit,Male,40.0,67.0,NaN,211.0,645.0,300.0,NaN,196.0,NaN,NaN,245.0,200.0,375.0,325.0,25.0,I eat 1-3 full cheat meals per week|,I workout mostly at a CrossFit Affiliate|I hav...,I played youth or high school level sports|,I began CrossFit by trying it alone (without a...,I usually only do 1 workout a day|,4+ years|
4,5286.0,Bryce Abbey,NaN,NaN,NaN,Male,32.0,65.0,149.0,206.0,465.0,NaN,1053.0,NaN,NaN,1081.0,205.0,150.0,NaN,325.0,50.0,I eat quality foods but don't measure the amount|,I workout mostly at a CrossFit Affiliate|I inc...,I played college sports|,I began CrossFit by trying it alone (without a...,I usually only do 1 workout a day|I strictly s...,1-2 years|

In [21]:
# copying data to new df so original does not get manipulated
df1 = df.copy() # Copying df into df1
df1.head() # Verifiying df1

,athlete_id,name,region,team,affiliate,gender,age,height,weight,fran,helen,grace,filthy50,fgonebad,run400,run5k,candj,snatch,deadlift,backsq,pullups,eat,train,background,experience,schedule,howlong
0,2554.0,Pj Ablang,South West,Double Edge,Double Edge CrossFit,Male,24.0,70.0,166.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,220.0,NaN,400.0,305.0,NaN,NaN,I workout mostly at a CrossFit Affiliate|I hav...,I played youth or high school level sports|I r...,I began CrossFit with a coach (e.g. at an affi...,I do multiple workouts in a day 2x a week|,4+ years|
1,3517.0,Derek Abdella,NaN,NaN,NaN,Male,42.0,70.0,190.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have a coach who determines my programming|I...,I played youth or high school level sports|,I began CrossFit with a coach (e.g. at an affi...,I do multiple workouts in a day 2x a week|,4+ years|
2,4691.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5164.0,Abo Brandon,Southern California,LAX CrossFit,LAX CrossFit,Male,40.0,67.0,NaN,211.0,645.0,300.0,NaN,196.0,NaN,NaN,245.0,200.0,375.0,325.0,25.0,I eat 1-3 full cheat meals per week|,I workout mostly at a CrossFit Affiliate|I hav...,I played youth or high school level sports|,I began CrossFit by trying it alone (without a...,I usually only do 1 workout a day|,4+ years|
4,5286.0,Bryce Abbey,NaN,NaN,NaN,Male,32.0,65.0,149.0,206.0,465.0,NaN,1053.0,NaN,NaN,1081.0,205.0,150.0,NaN,325.0,50.0,I eat quality foods but don't measure the amount|,I workout mostly at a CrossFit Affiliate|I inc...,I played college sports|,I began CrossFit by trying it alone (without a...,I usually only do 1 workout a day|I strictly s...,1-2 years|

In [22]:
### Step 2 ###

#droping unwanted columns
df1.drop(columns=['athlete_id','name','team','affiliate'],inplace=True) # droping selected columns from df1
df1.head() # verifiying df1

,region,gender,age,height,weight,fran,helen,grace,filthy50,fgonebad,run400,run5k,candj,snatch,deadlift,backsq,pullups,eat,train,background,experience,schedule,howlong
0,South West,Male,24.0,70.0,166.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,220.0,NaN,400.0,305.0,NaN,NaN,I workout mostly at a CrossFit Affiliate|I hav...,I played youth or high school level sports|I r...,I began CrossFit with a coach (e.g. at an affi...,I do multiple workouts in a day 2x a week|,4+ years|
1,NaN,Male,42.0,70.0,190.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have a coach who determines my programming|I...,I played youth or high school level sports|,I began CrossFit with a coach (e.g. at an affi...,I do multiple workouts in a day 2x a week|,4+ years|
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Southern California,Male,40.0,67.0,NaN,211.0,645.0,300.0,NaN,196.0,NaN,NaN,245.0,200.0,375.0,325.0,25.0,I eat 1-3 full cheat meals per week|,I workout mostly at a CrossFit Affiliate|I hav...,I played youth or high school level sports|,I began CrossFit by trying it alone (without a...,I usually only do 1 workout a day|,4+ years|
4,NaN,Male,32.0,65.0,149.0,206.0,465.0,NaN,1053.0,NaN,NaN,1081.0,205.0,150.0,NaN,325.0,50.0,I eat quality foods but don't measure the amount|,I workout mostly at a CrossFit Affiliate|I inc...,I played college sports|,I began CrossFit by trying it alone (without a...,I usually only do 1 workout a day|I strictly s...,1-2 years|

In [23]:
### Step 3 ###

#dealing with Nan values
df1.isnull().sum() * 100 /len(df1) # Checking percentage of null values in each column

region        40.600843
gender        21.724515
age           21.724515
height        62.206446
weight        45.653253
fran          86.897113
helen         92.841946
grace         90.367749
filthy50      95.423469
fgonebad      92.969840
run400        94.740973
run5k         91.466551
candj         75.311225
snatch        77.002690
deadlift      72.737266
backsq        73.873420
pullups       88.036104
eat           77.794168
train         74.981206
background    76.609079
experience    75.192787
schedule      76.862030
howlong       74.183345
dtype: float64

In [24]:
# Checking columns with large number of Nan values
df1.columns[df1.isnull().sum() * 100 /len(df1) > 70] # Displaying columns where null values are greater than 70%

Index(['fran', 'helen', 'grace', 'filthy50', 'fgonebad', 'run400', 'run5k',
       'candj', 'snatch', 'deadlift', 'backsq', 'pullups', 'eat', 'train',
       'background', 'experience', 'schedule', 'howlong'],
      dtype='object')

In [25]:
# Checking shape of df1
df1.shape

(423006, 23)

- As we can see 18 out of 23 columns have null values greater then 70%, So instead of imputing null values we will simply be dropping them

In [26]:
# dropping null values
df1=df1.dropna() # dropping all null values in df1
df1.isnull().sum() * 100 / len(df1) # checking for any remaining null values

region        0.0
gender        0.0
age           0.0
height        0.0
weight        0.0
fran          0.0
helen         0.0
grace         0.0
filthy50      0.0
fgonebad      0.0
run400        0.0
run5k         0.0
candj         0.0
snatch        0.0
deadlift      0.0
backsq        0.0
pullups       0.0
eat           0.0
train         0.0
background    0.0
experience    0.0
schedule      0.0
howlong       0.0
dtype: float64

In [27]:
### Step 3 ###
# feature engineering

df2 = df1.copy() # copying df1 into df2 for purpose of feature engineering

# dividing eat column into 3 groups strict diet, normal diet and no diet

# creating a function to divide eat column into 3 groups

def eat(x):
    # function should check wehter a part of string is in eat column and return a string
    if x == "I eat quality foods but don't measure the amount|":
        return 'normal diet'
    elif x == 'I eat whatever is convenient|':
        return 'no diet'
    elif 'I eat strict Paleo|' in x:
       return 'strict diet'
    elif 'I eat whatever is convenient' and 'I eat strict Paleo' in x:
        return 'no diet'
    elif 'I eat quality foods' and 'I eat strict Paleo' in x:
        return 'strict diet'
    elif 'I eat quality foods' and 'I eat strict Paleo' in x:
        return 'strict diet'
    elif 'I eat quality foods' and 'I eat whatever is convenient' in x:
        return 'no diet'
    elif 'I weigh and measure my food' in x:
        return 'normal diet'
    elif 'I eat quality foods' in x:
        return 'normal diet'
    elif x == 'Decline to answer|':
        return 'Decline to answer'
    else:
        return 'normal diet'
    
# applying function to eat column
df2['eat']=df2['eat'].apply(eat) # applying function to eat column and storing it in eat column

In [28]:
df2['eat'].value_counts() # checking value counts of eat column

normal diet          1172
no diet               298
strict diet           149
Decline to answer      21
Name: eat, dtype: int64

In [29]:
# verifying df2
df2.head()

,region,gender,age,height,weight,fran,helen,grace,filthy50,fgonebad,run400,run5k,candj,snatch,deadlift,backsq,pullups,eat,train,background,experience,schedule,howlong
102,South Central,Male,24.0,68.0,180.0,126.0,449.0,86.0,988.0,425.0,58.0,1302.0,315.0,240.0,475.0,405.0,80.0,normal diet,I workout mostly at a CrossFit Affiliate|I hav...,I played youth or high school level sports|,I began CrossFit with a coach (e.g. at an affi...,I do multiple workouts in a day 3+ times a wee...,2-4 years|
110,South West,Male,31.0,67.0,150.0,244.0,486.0,294.0,1217.0,330.0,63.0,1268.0,230.0,175.0,410.0,330.0,42.0,normal diet,I workout mostly at a CrossFit Affiliate|I inc...,I played college sports|,I began CrossFit by trying it alone (without a...,I usually only do 1 workout a day|I do multipl...,2-4 years|
116,Mid Atlantic,Male,37.0,72.0,210.0,162.0,482.0,143.0,1243.0,366.0,66.0,1320.0,285.0,205.0,525.0,425.0,49.0,normal diet,I workout mostly at a CrossFit Affiliate|I inc...,I played youth or high school level sports|I p...,I began CrossFit with a coach (e.g. at an affi...,I do multiple workouts in a day 2x a week|I ty...,4+ years|
205,Latin America,Male,25.0,71.0,180.0,193.0,498.0,146.0,1584.0,263.0,93.0,1406.0,260.0,225.0,405.0,320.0,30.0,no diet,I workout mostly at a CrossFit Affiliate|I hav...,I have no athletic background besides CrossFit|,I began CrossFit with a coach (e.g. at an affi...,I do multiple workouts in a day 1x a week|I st...,2-4 years|
224,Europe,Male,27.0,69.0,192.0,147.0,480.0,100.0,1070.0,0.0,67.0,1340.0,287.0,220.0,441.0,397.0,30.0,no diet,I workout mostly at a CrossFit Affiliate|,I played college sports|,I began CrossFit with a coach (e.g. at an affi...,I do multiple workouts in a day 3+ times a wee...,2-4 years|

In [30]:
df2.shape

(1640, 23)

In [31]:
### defining functions for all other columns reqiured for feaature engineering
# creating a function to divide train column into  groups

def train(x):
    # function should check wehter a part of string is in train column and return a string
    if 'I workout mostly at a CrossFit Affiliate' and 'I incorporate CrossFit.com workouts' in x:
        return 'CF center and CFWO'
    elif 'I workout mostly at a CrossFit Affiliate' and 'I have a coach who determines my programming' in x:
        return 'CF center and Non CFWO'
    elif 'I incorporate CrossFit.com workouts' and 'I workout mostly at home, work, or a traditional gym' in x:
        return 'Non CF center CFWO'
    elif 'I workout mostly at home, work, or a traditional gym' and 'I have a coach who determines my programming' in x:
        return 'Non CF center and Non CFWO'
    elif 'I workout mostly at home, work, or a traditional gym' in x:
        return 'Non CF center'
    elif 'I workout mostly at a CrossFit Affiliate' in x:
        return 'CF center'
    elif 'I incorporate CrossFit.com workouts' in x:
        return 'CFWO'
    else :
        return 'Non CF center and Non CFWO'
    
# creating function to divide background column into  groups

def background(x):
    # function should check wehter a part of string is in background column and return a string
    if x == 'I have no athletic background besides CrossFit|':
        return 'Only CF'
    elif 'I played professional sports' in x:
        return 'Professional sports'
    elif 'I regularly play recreational sports' in x:
        return 'Regular rec sports'
    elif x == 'Decline to answer|':
        return 'Decline to answer'
    else:
        return 'Educational institute sports'
    
# creating function to divide experience column into  groups

def experience(x):
    # function should check wehter a part of string is in experience column and return a string
    if x == 'I began CrossFit with a coach (e.g. at an affiliate)|':
        return 'With coach'
    elif x == 'I began CrossFit by trying it alone (without a coach)|':
        return 'Without coach'
    elif x == 'Decline to answer|':
        return 'Decline to answer'
    elif 'I train other people' in x:
        return 'Trainer'
    elif 'I have attended one or more specialty courses' in x:
        return 'Speciality courses'
    elif 'I have completed the CrossFit Level 1 certificate course' in x:
        return 'Level 1'
    else:
        return 'Other'
    
# creating function to divide schedule column into  groups

def schedule(x):
    # function should check wehter a part of string is in schedule column and return a string
    if 'I do multiple workouts in a day 3+ times a week' in x:
        return '3+ a week'
    elif 'I do multiple workouts in a day 2x a week' in x:
        return '2x a week'
    elif 'I usually only do 1 workout a day' in x:
        return '1x a day'
    elif x=='Decline to answer|':
        return 'Decline to answer'
    else:
        return 'Other'

# creating function to divide howlong column into  groups 

def howlong(x):
    # function should check wehter a part of string is in howlong column and return a string
    if '4+ years' in x:
        return '4+ years'
    elif '2-4 years' in x:
        return '2-4 years'
    elif '1-2 years' in x:
        return '1-2 years'
    elif '6-12 months' in x:
        return '6-12 months'
    elif 'Less than 6 months' in x:
        return 'Less than 6 months'
    elif x=='Decline to answer|':
        return 'Decline to answer'
    else:
        return 'Other'

In [32]:
## applying functions to respective columns
df2['train']=df2['train'].apply(train) # applying function to train column and storing it in train column
df2['background']=df2['background'].apply(background) # applying function to background column and storing it in background column
df2['experience']=df2['experience'].apply(experience) # applying function to experience column and storing it in experience column
df2['schedule']=df2['schedule'].apply(schedule) # applying function to schedule column and storing it in schedule column
df2['howlong']=df2['howlong'].apply(howlong) # applying function to howlong column and storing it in howlong column
df2.head() # checking df2

,region,gender,age,height,weight,fran,helen,grace,filthy50,fgonebad,run400,run5k,candj,snatch,deadlift,backsq,pullups,eat,train,background,experience,schedule,howlong
102,South Central,Male,24.0,68.0,180.0,126.0,449.0,86.0,988.0,425.0,58.0,1302.0,315.0,240.0,475.0,405.0,80.0,normal diet,CF center and Non CFWO,Educational institute sports,Trainer,3+ a week,2-4 years
110,South West,Male,31.0,67.0,150.0,244.0,486.0,294.0,1217.0,330.0,63.0,1268.0,230.0,175.0,410.0,330.0,42.0,normal diet,CF center and CFWO,Educational institute sports,Trainer,3+ a week,2-4 years
116,Mid Atlantic,Male,37.0,72.0,210.0,162.0,482.0,143.0,1243.0,366.0,66.0,1320.0,285.0,205.0,525.0,425.0,49.0,normal diet,CF center and CFWO,Regular rec sports,Trainer,2x a week,4+ years
205,Latin America,Male,25.0,71.0,180.0,193.0,498.0,146.0,1584.0,263.0,93.0,1406.0,260.0,225.0,405.0,320.0,30.0,no diet,CF center and CFWO,Only CF,Trainer,Other,2-4 years
224,Europe,Male,27.0,69.0,192.0,147.0,480.0,100.0,1070.0,0.0,67.0,1340.0,287.0,220.0,441.0,397.0,30.0,no diet,CF center,Educational institute sports,Trainer,3+ a week,2-4 years

In [33]:
df2.isnull().sum() # checking if any null values in df2

region        0
gender        0
age           0
height        0
weight        0
fran          0
helen         0
grace         0
filthy50      0
fgonebad      0
run400        0
run5k         0
candj         0
snatch        0
deadlift      0
backsq        0
pullups       0
eat           0
train         0
background    0
experience    0
schedule      0
howlong       0
dtype: int64

In [36]:
#converting numerical columns from float to int
df2['age']=df2['age'].astype(int) # converting age column from float to int
df2['height']=df2['height'].astype(int) # converting height column from float to int
df2['weight']=df2['weight'].astype(int) # converting weight column from float to int
df2['fran']=df2['fran'].astype(int) # converting fran column from float to int
df2['helen']=df2['helen'].astype(int) # converting helen column from float to int
df2['grace']=df2['grace'].astype(int) # converting grace column from float to int
df2['filthy50']=df2['filthy50'].astype(int) # converting filthy50 column from float to int
df2['fgonebad']=df2['fgonebad'].astype(int) # converting fgonebad column from float to int
df2['run400']=df2['run400'].astype(int) # converting run400 column from float to int
df2['run5k']=df2['run5k'].astype(int) # converting run5k column from float to int
df2['candj']=df2['candj'].astype(int) # converting candj column from float to int
df2['snatch']=df2['snatch'].astype(int) # converting snatch column from float to int
df2['deadlift']=df2['deadlift'].astype(int) # converting deadlift column from float to int
df2['backsq']=df2['backsq'].astype(int) # converting backsq column from float to int
df2['pullups']=df2['pullups'].astype(int) # converting pullups column from float to int

In [34]:
# # feature engineering age column into age groups
# # creating a function to divide age column into  groups
# def age(x):
#     # function should check wehter a part of string is in age column and return a string
#     if x <= 18:
#         return 'teen'
#     elif x > 18 and x <= 25:
#         return 'young adult'
#     elif x > 25 and x <= 35:
#         return 'adult'
#     elif x > 35 and x <= 55:
#         return 'middle age'
#     elif x > 55:
#         return 'old'
#     elif x == 'Decline to answer|':
#         return 'Decline to answer'
#     else:
#         return 'other'
# # applying function to age column
# df2['age']=df2['age'].apply(age) # applying function to age column and storing it in age column
# df2.head() # checking df2

In [38]:
df2.to_csv('cleaned_athletes.csv') # saving df2 as csv file